"""User-facing explanation prototype — judgment augmentation, not buy/sell."""

from __future__ import annotations

from typing import Any


def render_explanation_prototype_md(
    *,
    hypothesis: dict[str, Any],
    signal_case: dict[str, Any],
) -> str:
    """
    One hypothesis + one concrete signal row (e.g. fixture symbol) → draft MD surface.
    """
    hid = hypothesis.get("hypothesis_id", "")
    title = hypothesis.get("title", "")
    thesis = hypothesis.get("economic_thesis", "")
    mechanism = hypothesis.get("expected_mechanism", "")
    falsifiers = hypothesis.get("falsifiers") or []
    sym = signal_case.get("symbol", "")
    bucket = signal_case.get("residual_join_bucket", "")
    blocked = signal_case.get("blocked_reason", "")
    sigd = signal_case.get("signal_available_date", "")
    sc_as_of = signal_case.get("first_state_change_as_of_in_run", "")

    fals_lines = "\n".join(f"- {f}" for f in falsifiers) if falsifiers else "- (none listed)"

    return f"""# Explanation prototype — `{sym}` under `{hid}`

## What changed (observable)

- Substrate audit classifies **{sym}** as **`{bucket}`** with signal date **{sigd}**.
- Referenced state_change grid’s earliest as_of in the audit run is **{sc_as_of}**, yielding **`{blocked}`** under the default join rule.

## Why it may matter (judgment, not advice)

- {thesis}

## Mechanism under test

- {mechanism}

## Evidence supporting the framing

- Deterministic audit fields above are reproduced from the **PIT-lab fixture** (Phase 36.1 residual set), not a model guess.
- Hypothesis **{title}** ties the residual to **as-of / run reference** rather than “missing data” narratives.

## What remains uncertain

- Alternate **PIT run specs** (explicit in the experiment scaffold) are **not yet DB-executed** — this text is a **prototype surface** only.
- Economic interpretation of the signal row is **out of scope** until the PIT harness compares alternate boundaries without leakage.

## Why this is not a black-box recommendation

- No score or action is produced here; the object is **transparent classification** + **falsifiable hypotheses** + **deferred adversarial review** items.
- Promotion to any user-facing “signal” would require **promotion gate** artifacts not auto-generated by this sprint.

## Falsifiers (hypothesis)

{fals_lines}
"""
